Add friends likes
Niks5041/java-filmorate pull request #7
Opened 2024-06-27 10:38 UTC by Niks5041

2024-06-27 19:15 UTC, YazykovMikhail requested changes

2024-06-28 14:36 UTC, Niks5041 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void checkValid(Film film) {
Не до конца понял, тогда вынести все вызовы метода сторадж в сервис с проверками?
или достаточно вызывать в сторадже у сервиса метод проверки
сделал 2 вариант

2024-06-29 11:41 UTC, YazykovMikhail approved these changes

2024-06-29 11:41 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        checkValidService(existUser, existFilm);
Название метода должно описывать что оно делатся или для чего
А тут получается "проверить валидацию сервиса" несовсем понятно что это и что там

2024-07-06 15:01 UTC, merged